alias ..='cd ..'
alias bashrc='$EDITOR ~/.bashrc && source ~/.bashrc'
alias bash_aliases='$EDITOR ~/.bash_aliases && source ~/.bash_aliases'
alias aliases='$EDITOR ~/.bash_aliases && source ~/.bash_aliases'
alias profile='$EDITOR ~/.profile && source ~/.profile'
alias rm='rm -I'
alias df='df -h'
