" tabs to spaces
set softtabstop=4

" Tabs are space
set expandtab

" line numbers
set number

" Cursor line highlight 
set cursorline

" show command
set showcmd

" filetype detection
filetype indent on

" autocompletion
set wildmenu

" search tweaks
set incsearch
set hlsearch

" yank to system clipboard - requires xclip or xsel
set clipboard+=unnamedplus

" Environment
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

