[theme]
name = "gruvbox-dark"

[icons]
name = "material-nf_bat_patch"

[theme.overrides]
separator = ""
idle_bg = "#3c3836"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "\u2328 {variant}"

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "ok"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"
hide_when_uptodate = true

# [[block]]
# block = "backlight"
# device = "intel_backlight"

[[block]]
block = "battery"
interval = 10
hide_missing = true
allow_missing = true
[block.theme_overrides]
idle_bg = "#504945"

[[block]]
block = "networkmanager"
primary_only = true
on_click = "nm-connection-editor"
ap_format = "{freq}"
device_format = "{icon}{name}"
[block.theme_overrides]
good_bg = "#504945"

[[block]]
block = "sound"
step_width = 5
[block.theme_overrides]
idle_bg = "#665c65"

[[block]]
block = "time"
format = "%Y-%m-%d │ %I:%M %p"
timezone = "US/Central"
interval = 60
locale = "en_US"
[block.theme_overrides]
idle_bg = "#7c6f64"

# Launcher block
[[block]]
block = "custom"
command = 'echo ""'
on_click = 'swaymsg "exec alacritty --class=launcher -e /usr/bin/sway-launcher-desktop"'
[block.theme_overrides]
idle_bg = "#d79921"

# Lock, reboot, power blocks
[[block]]
block = "custom"
command = 'echo ""'
on_click = "exec swaynagmode -t warning -m '' -b 'Logout' 'swaymsg exit' -b 'Reboot' 'systemctl reboot' -b 'Power off' 'systemctl -i poweroff'"
[block.theme_overrides]
idle_bg = "#d79921"

# Empty block for tray separator
[[block]]
block = "custom"
command = 'echo ""'
[block.theme_overrides]
idle_bg = "#282828"

