[theme]
name = "gruvbox-dark"

[icons]
name = "material-nf_bat_patch"

[theme.overrides]
separator = ""
idle_bg = "#504945"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "ok"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"
hide_when_uptodate = true

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "\u2328 {variant}"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "{icon} {available}"
interval = 60
alert = 25
warning = 50
alert_absolute = true

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

# [[block]]
# block = "backlight"
# device = "intel_backlight"

[[block]]
block = "battery"
interval = 10
hide_missing = true
allow_missing = true
[block.theme_overrides]

[[block]]
block = "networkmanager"
primary_only = true
on_click = "foot -e nmtui"
ap_format = "{freq}"
device_format = "{icon}{name}"
[block.theme_overrides]
good_bg = "#504945"
info_bg = "#504945"

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
format = "%Y-%m-%d │ %I:%M %p"
timezone = "US/Central"
interval = 60
locale = "en_US"
[block.theme_overrides]
idle_bg = "#665c54"

# terminal, browser, launcher, lock, reboot, power blocks
[[block]]
block = "custom"
command = 'echo ""'
on_click = 'swaymsg "exec foot"'
[block.theme_overrides]
idle_bg = "#d79921"

[[block]]
block = "custom"
command = 'echo "爵"'
on_click = 'exec firefox'
[block.theme_overrides]
idle_bg = "#d79921"

[[block]]
block = "custom"
command = 'echo ""'
on_click = 'exec foot -e vifm'
[block.theme_overrides]
idle_bg = "#d79921"

[[block]]
block = "custom"
command = 'echo ""'
on_click = 'swaymsg "exec foot --app-id=launcher -e /usr/bin/sway-launcher-desktop"'
[block.theme_overrides]
idle_bg = "#d79921"

[[block]]
block = "custom"
command = 'echo ""'
on_click = "exec swaynagmode --font 'SF Pro Display' -t warning -m '' -b ' Lock ' 'swaylock -f -c 000000' -b ' Logout ' 'swaymsg exit' -b ' Reboot ' 'systemctl reboot' -b ' Power off ' 'systemctl -i poweroff'"
[block.theme_overrides]
idle_bg = "#d79921"

