alias ..='cd ..'
alias bashrc='$EDITOR ~/.bashrc && source ~/.bashrc'
alias bash_aliases='$EDITOR ~/.config/.bash_aliases && source ~/.bash_aliases'
alias aliases='$EDITOR ~/.config/.bash_aliases && source ~/.config/.bash_aliases'
alias profile='$EDITOR ~/.profile && source ~/.profile'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -I'
alias df='df -h'
alias du='du -h'
alias ls='ls -l'
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -CF'
alias R='R --no-save --no-restore-data'
alias open='xdg-open'

# System specific commands
alias vivo='sudo python vivosmart/send_command.py'
alias tuir='conda activate tuir && tuir && conda deactivate'
alias scc='sc-controller-0.4.7/run.sh'
