#!/bin/sh

alias cp="cp -iv"                                               # Confirm before overwriting something
alias df='df -h'                                                # Human-readable sizes
alias free='free -m'                                            # Show sizes in MB
alias gitu='git add . && git commit && git push'
alias ..='cd ..'
alias mv='mv -iv'
alias rm='rm -I'
alias du='du -h'
alias ls='ls -l'
alias open='xdg-open'
alias vim='nvim'
alias v='nvim'
alias e='$EDITOR'
alias r='radian --no-history'
alias ms='mullvad status'
alias mh='mullvad_helper'
alias mutt='mbsync vfaner && neomutt'
alias tmux='tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf'
alias unlock='loginctl unlock-sessions'
alias dlalbum='youtube-dl --ignore-errors -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"'
alias kpc='keepassxc-cli clip ~/Sync/Stuff/KeePass.kdbx'
alias deconda='conda deactivate'
alias condact='conda activate'

# Used for $HOME cleanup
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias mbsync='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='exa -l --color=auto'
    alias ll='exa -al --color=auto --git'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias diff='diff --color=auto'
    alias ip='ip -color=auto'
fi

