[colors.bright]
black = "#C6C3C3"
red = "#94253E"
green = "#3F5A22"
yellow = "#803D1C"
blue = "#1D5573"
magenta = "#7B3B70"
cyan = "#2B747C"
white = "#5C5C5C"

[colors.cursor]
cursor = "#000000"
text = "#FFFFFF"

[colors.normal]
black = "#FFFFFF"
blue = "#286486"
cyan = "#3B8992"
green = "#4F6C31"
magenta = "#88507D"
red = "#A8334C"
white = "#353535"
yellow = "#944927"

[colors.primary]
background = "#FFFFFF"
foreground = "#000000"

[cursor]
blink_interval = 600
vi_mode_style = "block"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[scrolling]
history = 50000

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "none"
padding = { x = 30, y = 30 }

