# Default colors
[colors.primary]
background = '#F9F5D6'
foreground = '#282828'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#F9F5D6'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#3c3836'
red     = '#9d0006'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#076678'
magenta = '#8f3f71'
cyan    = '#427b58'
white   = '#F9F5D6'

[cursor]
blink_interval = 600
vi_mode_style = "block"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[scrolling]
history = 50000

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
padding = { x = 30, y = 30 }

