[tools]
fzf = "latest"
ripgrep = "latest"
bat = "latest"
bottom = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
jq = "latest"
rust = "latest"
go = "latest"
node = "latest"
python = "latest"
pipx = "latest"
uv = "latest"
ollama = "latest"

"npm:vscode-langservers-extracted" = "latest"
"npm:bash-language-server" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:prettier" = "latest"

"pipx:ruff" = "latest"
"pipx:isort" = "latest"
"pipx:black" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:visidata" = "latest"
"pipx:radian" = "latest"
"pipx:debugpy" = "latest"
"pipx:basedpyright" = "latest"
"pipx:pylyzer" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
