[tools]
fzf = "latest"
ripgrep = "latest"
bat = "latest"
bottom = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
jq = "latest"
rust = "latest"
go = "latest"
node = "latest"
python = "latest"
pipx = "latest"
uv = "latest"
ollama = "latest"
yarn = "latest"
delta = "latest"
difftastic = "latest"
usql = "latest"

"npm:vscode-langservers-extracted" = "latest"
"npm:bash-language-server" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:prettier" = "latest"
"npm:azure-pipelines-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:vim-language-server" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:dot-language-server" = "latest"

"pipx:ruff" = "latest"
"pipx:isort" = "latest"
"pipx:black" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:visidata" = "latest"
"pipx:radian" = "latest"
"pipx:basedpyright" = "latest"
"pipx:pylyzer" = "latest"
"pipx:jupytext" = "latest"
"pipx:nbdime" = "latest"
"pipx:databricks-sql-cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
python.uv_venv_auto = true
experimental = true

